In [ ]:
import pandas as pd
df = pd.read_csv('Imbalanced_data.csv') 
df.head()

   2.220137062062631506e-01  5.402065352570863954e-01  0.000000000000000000e+00
0                  1.347439                  1.412824                       0.0
1                  0.537238                  0.372730                       0.0
2                  2.134462                  1.404819                       0.0
3                  2.315827                  1.356858                       0.0
4                  1.205043                  0.780961                       0.0

In [ ]:
df.shape

(9999, 3)

In [ ]:
df.columns = ['X_column' , 'Y_column', 'Outcome']

In [ ]:
df

      X_column  Y_column  Outcome
0     1.347439  1.412824      0.0
1     0.537238  0.372730      0.0
2     2.134462  1.404819      0.0
3     2.315827  1.356858      0.0
4     1.205043  0.780961      0.0
...        ...       ...      ...
9994  2.440385  1.695643      0.0
9995 -0.790502  0.194243      0.0
9996  1.878130  0.829500      0.0
9997  2.585933  1.927995      0.0
9998  1.123356  1.045755      0.0

[9999 rows x 3 columns]

In [ ]:
df.value_counts()

X_column   Y_column  Outcome
 4.447943  2.422662  0.0        1
 0.568086  0.927183  0.0        1
 0.570000  1.462936  0.0        1
 0.569527  0.973115  0.0        1
 0.569002  0.799359  0.0        1
                               ..
 1.377484  0.706270  0.0        1
 1.377443  1.358088  0.0        1
 1.377052  1.298715  0.0        1
 1.377004  1.555590  0.0        1
-3.091974  0.507565  1.0        1
Length: 9999, dtype: int64

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(X)

      X_column  Y_column
0     1.347439  1.412824
1     0.537238  0.372730
2     2.134462  1.404819
3     2.315827  1.356858
4     1.205043  0.780961
...        ...       ...
9994  2.440385  1.695643
9995 -0.790502  0.194243
9996  1.878130  0.829500
9997  2.585933  1.927995
9998  1.123356  1.045755

[9999 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
X['X_column'] = lb.fit_transform(X['X_column'])
X['Y_column'] = lb.fit_transform(X['Y_column'])
print(X)

      X_column  Y_column
0         6539      8151
1         3226       922
2         8953      8103
3         9246      7831
4         5953      3223
...        ...       ...
9994      9406      9336
9995       325       414
9996      8363      3592
9997      9565      9763
9998      5603      5438

[9999 rows x 2 columns]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
from sklearn.model_selection import train_test_split 
X_train , X_test ,y_train ,y_test = train_test_split(X , y , test_size = 0.3 , random_state = 10)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
model = KNeighborsClassifier() 
model.fit(X_train , y_train) 
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score 
print(accuracy_score(y_test, y_pred))

0.9926666666666667

In [ ]:
pd.crosstab(y_test , y_pred)

col_0     0.0  1.0
Outcome
0.0      2969    0
1.0        22    9

In [ ]:
2969/2969 #this is for majority class and accuracy is 100 percent

1.0

In [ ]:
9/31 #this is for minority class. So, now we will apply SMOTE

0.2903225806451613

In [ ]:
pip install imblearn

Requirement already satisfied: imblearn in /usr/local/lib/python3.7/dist-packages (0.0)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.7/dist-packages (from imblearn) (0.8.1)
Requirement already satisfied: scikit-learn>=0.24 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn->imblearn) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn->imblearn) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn->imblearn) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn->imblearn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24->imbalanced-learn->imblearn) (3.0.0)

In [ ]:
from imblearn.over_sampling import BorderlineSMOTE
bpsmote = BorderlineSMOTE()

In [ ]:
X_train_bpsmote , y_train_bpsmote = bpsmote.fit_resample(X_train.astype('float') , y_train)

In [ ]:
from collections import Counter 
print('Before BorederlineSMOTE :' , Counter(y_train))
print('After BorderlineSMOTE :' , Counter(y_train_bpsmote))

Before BorederlineSMOTE : Counter({0.0: 6930, 1.0: 69})
After BorderlineSMOTE : Counter({0.0: 6930, 1.0: 6930})

In [ ]:
model.fit(X_train_bpsmote , y_train_bpsmote) 
y_pred = model.predict(X_test) 
print(accuracy_score(y_test, y_pred))
pd.crosstab(y_test , y_pred)

0.9753333333333334

col_0     0.0  1.0
Outcome
0.0      2902   67
1.0         7   24

In [ ]:
2902/2969 # the majority class accuracy becomes 97 percent after BorderlineSMOTE

0.9774334792859549

In [ ]:
24/31 #the minority class accuracy becomes 77 percent after BorderlineSMOTE

0.7741935483870968